public class OpenCvInterface {
	boolean ifThePositionOfTheRobotHappensToBeInFrontOfALocationThatIsInFrontOfTheSkystoneReturnTrueOtherwiseItWillReturnFalseEndOfSentanceWhyAreYouStillReadingYouShouldStopNowYouIdiot() {
		return false;
	}
}